version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pag123
      - MYSQL_DATABASE=dbpag
  rabbitmq:
    image: rabbitmq:3.9.7-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
    - RABBITMQ_DEFAULT_USER=admin
    - RABBITMQ_DEFAULT_PASS=123456